image: node:10

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

.Build template: &build_template
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    name: build
    paths:
      - build

Dev build:
  only:
    refs:
      - development
  <<: *build_template

Dev deploy:
  image: python:latest
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 sync build s3://$DEV_AWS_BUCKET_NAME
  only:
    refs:
      - development
    changes:
      - src/**/*
      - static/**/*
      - content/**/*
      - package.json
      - package-lock.json
      - .gitlab-ci.yml
  dependencies:
    - Dev build
