image: node:10

stages:
  - build
  - deploy

Build Job:
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    name: build
    paths:
      - build

Deploy Job:
  stage: deploy
  before_script:
    - apt install python3-pip
    - pip3 install awscli
  script:
    - aws s3 sync build/ s3://$REACT_APP_AWS_S3_BUCKET_URL
  only:
    refs:
      - master
    changes:
      - src/**/*
      - static/**/*
      - content/**/*
      - package.json
      - package-lock.json
      - .gitlab-ci.yml
  variables:
    REACT_APP_API_BASE_URL: $DEV_REACT_APP_API_BASE_URL
    REACT_APP_AWS_S3_BUCKET_URL: $DEV_REACT_APP_AWS_S3_BUCKET_URL
    REACT_APP_AWS_S3_ACCESS_KEY_ID: $DEV_REACT_APP_AWS_S3_ACCESS_KEY_ID
    REACT_APP_AWS_S3_SECRET_ACCESS_KEY: $DEV_REACT_APP_AWS_S3_SECRET_ACCESS_KEY

