image: node:10
stages:
  - build
  - deploy
Build Job:
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    name: build
    paths:
      - build
Deploy Job:
  stage: deploy
  script:
    - ls build
  environment:
    name: staging
    url: https://staging.example.com
  only:
    refs:
      - master
    changes:
      - src/**/*
      - static/**/*
      - content/**/*
      - package.json
      - package-lock.json
      - .gitlab-ci.yml
