image: node:10

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

Build Job:
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    name: build
    paths:
      - build

Deploy Job:
  stage: deploy
  before_script:
    - npm install aws-sdk
    - npm install -g aws-deploy-script-fe
  script:
    - aws-deploy
  only:
    refs:
      - master
    changes:
      - src/**/*
      - static/**/*
      - content/**/*
      - package.json
      - package-lock.json
      - .gitlab-ci.yml
