image: node:10

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

Build Job:
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    name: build
    paths:
      - build

Deploy Job:
  image: python:latest
  stage: deploy
  script:
    - echo $AWS_BUCKET_URL
    - echo $AWS_DEFAULT_REGION
    - pip install awscli
    - aws s3 sync build $AWS_BUCKET_URL --region $AWS_DEFAULT_REGION
  only:
    refs:
      - master
    changes:
      - src/**/*
      - static/**/*
      - content/**/*
      - package.json
      - package-lock.json
      - .gitlab-ci.yml
